### ISSUE TITLE
Check for user privileges during initialization

### ISSUE THREAD

**Issue by foxyseta** [geteduroam/linux-app#28]
Maybe user privileges should be checked at initialization. If they are not, the user wastes time of a lengthy workflow with no results.

**Comment by mrvanes** [comment]
I don't think user privileges play an important role, since we are setting user network-manager profiles?

**Comment by jwijenbergh** [comment]
@foxyseta Thanks for the issue. Do you meant that if the user is not in the NetworkManager group it will only show a fail at the end?

**Comment by foxyseta** [comment]
Well, I actually have a problem with my current setup that prevents any user without super-user privileges from tinkering with the network settings (even  after adding said user to the appropriate groups). So my problem is definitely unrealted to your project. Still, I would still find this a nice UX improvement.

**Comment by jwijenbergh** [comment]
I don't really see a good way to do this, other than inserting mock network entries (and later removing them) in networkmanager, which IMO is not a nice thing to do
