### ISSUE TITLE
Problem running the app

### ISSUE THREAD

**Issue by IsabelaCaldeira** [geteduroam/linux-app#33]
After downloading, I make the app allow to executive, but when I try to run it, it doesn't really work, should I try with some especif app or it should run in general?

**Comment by jwijenbergh** [comment]
Hi, thanks for making an issue. Did you download the CLI here https://github.com/geteduroam/linux-app/releases, I assume 
`geteduroam-cli-linux-amd64`? What happens if you run it? Which distribution and architecture?

**Comment by IsabelaCaldeira** [comment]
Yes, I dowloaded in the https://github.com/geteduroam/linux-app/releases. So it just doesn't run and it doesn't neither show a message of error or anything. 
I am using the ubuntu 22.04.3 LTS and the architecture is x86-64

**Comment by jwijenbergh** [comment]
Thanks. Are you double clicking the file in a file manager or sorts perhaps?

Could you trying opening a terminal and running it there? (`chmod +x ./geteduroam-cli-linux-amd64 && ./geteduroam-cli-linux-amd64`)

**Comment by IsabelaCaldeira** [comment]
I did with just one file at the time, when I tried now with both it did work!! I am connected now!

I hope everything works out with GUI for you guys!

Thank you very much!

**Comment by jwijenbergh** [comment]
Glad it works now, thanks!
