### ISSUE TITLE
Failed installation on Linux causes syslog spam

### ISSUE THREAD

**Issue by JSKenyon** [geteduroam/linux-app#42]
After attempting and failing to install the application from the nightly build (geteduroam-cli-linux-amd64) my syslog was spammed with messages which look like this:
```bash
Nov  1 09:21:25 jonathan org.freedesktop.FileManager1[2958754]: Please enter your organization (e.g. SURF): 
```
I was never presented with this option when attempting to install (in fact, the installer didn't present me with any options). This was likely an error on my part but it suggests that something isn't caught correctly. The message spam caused my syslog to grow to a problematic size.

Edit: Changed the above after I realised that problem was not persistent.

**Comment by jwijenbergh** [comment]
Is this not just the log that you double clicked on the CLI client in your file manager? You need to open the client in your terminal by navigating to the directory with `cd` and then run `./geteduroam-cli-linux-amd64` after making it executable with `chmod +x geteduroam-cli-linux-amd64`

**Comment by jwijenbergh** [comment]
Also if you prefer a GUI you can try the GUI package

**Comment by JSKenyon** [comment]
> Is this not just the log that you double clicked on the CLI client in your file manager? You need to open the client in your terminal by navigating to the directory with `cd` and then run `./geteduroam-cli-linux-amd64` after making it executable with `chmod +x geteduroam-cli-linux-amd64`

Absolutely - as I mentioned, it was a stupid error on my part. I thought it was worth raising anyway as it struck me as a sharp edge. In my case, it filled my OS partition by bloating the log. At the very least, there is now a trail of bread crumbs if any other user makes a similar error. Feel free to close the issue if you don't want to take further action and thank you for your quick response!

**Comment by jwijenbergh** [comment]
Ah yes indeed it does spam a lot. I will see if I can handle this, thanks!

**Comment by JSKenyon** [comment]
> Did the client work for you in the end?

It did, thank you!

**Comment by JSKenyon** [comment]
> Could you test the binary in https://github.com/geteduroam/linux-app/releases/tag/nightly I made a commit that hopefully handles this

Tested and I can confirm that it no longer spams the syslog when double clicked in executable mode.

**Comment by jwijenbergh** [comment]
Great! It should also send a notifcation if "notify-send" is installed.
