### ISSUE TITLE
Client authorization using the browser does not work with Firefox (has workaround)

### ISSUE THREAD

**Issue by mmterpstra** [geteduroam/linux-app#47]
Client authorization using the browser does not work with Firefox 122.0 (64-bit) snap on Ubuntu 22.04.
app version: nightly amd-64 cli build
```
Your browser has been opened to authorize the client
Or copy and paste the following url:  https://umcg.geteduroam.nl/oauth/authorize/?client_id=app.geteduroam.sh&code_challenge=...............
```

Workaround: 
Copypaste the url into Chromium instead of the default Firefox browser. 

Preferred solution:
Bundle own browser (web app) ? or warn about using firefox?

**Comment by jwijenbergh** [comment]
Hmmm, what doesn't work exactly with firefox?

**Comment by mmterpstra** [comment]
Hmm could be scripts being blocked or does the script expect some communication from the browser?

**Comment by jwijenbergh** [comment]
This is not an issue with this client, nor do I maintain that server. The authorize button itself works fine without javascript for me. Are you sure it's not because you're arriving at a microsoft portal that wants javascript to be enabled?
