### ISSUE TITLE
No worky on Arch Linux

### ISSUE THREAD

**Issue by vikingnope** [geteduroam/linux-app#50]
My friend is trying to use the CLI and GUI script on Arch, and it tells him the username and password have been saved on NetworkManager, but when trying to connect to the eduroam WIFI it goes through an infinite loop of asking for the credentials which never actually connect to the network.

Please help.

**Comment by jwijenbergh** [comment]
that means the credentials are not correct. Ensure they are correct, do the same credentials work on e.g. android?

**Comment by vikingnope** [comment]
Everything works fine on devices using Windows and Android, only on Arch Linux, and it's not just one person, I have another friend with the same issue.

**Comment by jwijenbergh** [comment]
please give the output of sudo journalctl -u NetworkManager (or could be called network-manager) when this happens

**Comment by jwijenbergh** [comment]
closing due to no response

**Comment by werty534tm** [comment]
Hello, having the same issue. I have tried the program with the exact same credentials on andriod and on arch. The only place where it doesnt connect me is on arch.
Journalctl output:
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2560] audit: op="connection-update" >
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2568] policy: auto-activating connec>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2591] device (wlp1s0): Activation: s>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2593] device (wlp1s0): state change:>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2867] device (wlp1s0): set-hw-addr: >
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2899] device (wlp1s0): state change:>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2905] device (wlp1s0): Activation: (>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2906] device (wlp1s0): state change:>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2926] device (wlp1s0): state change:>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2935] device (wlp1s0): state change:>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2941] device (wlp1s0): Activation: (>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2942] Config: added 'ssid' value 'ed>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2942] Config: added 'scan_ssid' valu>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2943] Config: added 'bgscan' value '>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2943] Config: added 'key_mgmt' value>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'proto' value 'R>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'pairwise' value>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'group' value 'C>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'password' value>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'eap' value 'TTL>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'fragment_size' >
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2944] Config: added 'phase2' value '>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2945] Config: added 'ca_cert' value >
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2945] Config: added 'altsubject_matc>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2945] Config: added 'identity' value>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2945] Config: added 'anonymous_ident>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.2945] Config: added 'proactive_key_c>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.3039] device (wlp1s0): supplicant in>
sep 11 11:38:59 ricoyogur NetworkManager[493]: <info>  [1726047539.3039] device (p2p-dev-wlp1s0): suppl>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.7799] device (wlp1s0): supplicant in>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.7800] device (p2p-dev-wlp1s0): suppl>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.7841] device (wlp1s0): supplicant in>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.7841] device (p2p-dev-wlp1s0): suppl>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.8010] device (wlp1s0): supplicant in>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.8010] device (p2p-dev-wlp1s0): suppl>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.9852] device (wlp1s0): supplicant in>
sep 11 11:39:00 ricoyogur NetworkManager[493]: <info>  [1726047540.9854] device (p2p-dev-wlp1s0): suppl>
sep 11 11:39:01 ricoyogur NetworkManager[493]: <info>  [1726047541.0851] device (wlp1s0): supplicant in>
sep 11 11:39:01 ricoyogur NetworkManager[493]: <info>  [1726047541.0853] device (p2p-dev-wlp1s0): suppl>

**Comment by falzuz** [comment]
I have a similar issue:

`Error: Connection activation failed: Secrets were required, but not provided
Hint: use 'journalctl -xe NM_CONNECTION=52cae50c-8dbf-4d53-ad7d-93a7a466660f + NM_DEVICE=wlan0' to get more details.`

**Comment by jwijenbergh** [comment]
Sorry I didn't see this. Can you both test the latest version? @falzuz @werty534tm

**Comment by Molier** [comment]
hi, ive used the program on arch steamos and some arch garuda linux distros, and it worked for me with current version.
if you could, maybe test out this installer script from this issue to see if that makes it perhaps easier: https://github.com/geteduroam/linux-app/issues/65 ?
(just chmod +x it and then run (perhaps sudo is needed))

**Comment by japhir** [comment]
I don't want to use a bash script that has so many lines dedicated to flair/colors/theming. It makes it harder for me to verify that nothing malicious is happening.
