### ISSUE TITLE
(geteduroam-gui:862662): Gtk-ERROR **: 17:57:13.057: failed to add UI: .:8:1 Invalid object type 'AdwToolbarView' SIGTRAP: trace trap

### ISSUE THREAD

**Issue by martinpescador** [geteduroam/linux-app#53]
I get this in Mint 21.3 / 6.8.0-45-generic #45~22.04.1-Ubuntu :

:~$ geteduroam-gui 

(geteduroam-gui:862662): Gtk-ERROR **: 17:57:13.057: failed to add UI: .:8:1 Invalid object type 'AdwToolbarView'
SIGTRAP: trace trap
PC=0x7d3acc927167 m=0 sigcode=128
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x6002a0, 0xc0004922a0)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc0004ac110 sp=0xc0004ac0d8 pc=0x4092eb
github.com/jwijenbergh/purego.RegisterFunc.func1({0xc000475320?, 0x2?, 0x2?})
	/home/runner/go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240126093400-70ff3a61df13/func.go:253 +0xc65 fp=0xc0004ac4f8 sp=0xc0004ac110 pc=0x5fe1e5
reflect.callReflect(0xc000000720, 0xc0004aca58, 0xc0004ac930, 0xc0004ac938)
	/opt/hostedtoolcache/go/1.21.8/x64/src/reflect/value.go:782 +0x54b fp=0xc0004ac8e0 sp=0xc0004ac4f8 pc=0x4d9f4b
reflect.callReflect(0xc000000720, 0xc0004aca58, 0xc0004ac930, 0xc0004ac938)
	<autogenerated>:1 +0x45 fp=0xc0004ac910 sp=0xc0004ac8e0 pc=0x4ea985
reflect.makeFuncStub()
	/opt/hostedtoolcache/go/1.21.8/x64/src/reflect/asm_amd64.s:47 +0x6e fp=0xc0004aca58 sp=0xc0004ac910 pc=0x4e6d0e
github.com/jwijenbergh/puregotk/v4/gtk.NewBuilderFromString({0xc0005c2600?, 0xc0005c0000?}, 0x25eb?)
	/home/runner/go/pkg/mod/github.com/jwijenbergh/puregotk@v0.0.0-20240305120901-acaa168affb9/v4/gtk/gtkbuilder.go:334 +0x1f fp=0xc0004aca88 sp=0xc0004aca58 pc=0x6e0e5f
main.(*ui).initBuilder(0xc000425f20)
	/home/runner/work/linux-app/linux-app/cmd/geteduroam-gui/main.go:354 +0x69 fp=0xc0004acac0 sp=0xc0004aca88 pc=0x995f09
main.(*ui).activate(0xc000425f20)
	/home/runner/work/linux-app/linux-app/cmd/geteduroam-gui/main.go:378 +0x18 fp=0xc0004acae0 sp=0xc0004acac0 pc=0x996298
main.(*ui).Run.func1({{0x0?}})
	/home/runner/work/linux-app/linux-app/cmd/geteduroam-gui/main.go:393 +0x17 fp=0xc0004acaf8 sp=0xc0004acae0 pc=0x9964d7
github.com/jwijenbergh/puregotk/v4/gio.(*Application).ConnectActivate.func1(0x0?)
	/home/runner/go/pkg/mod/github.com/jwijenbergh/puregotk@v0.0.0-20240305120901-acaa168affb9/v4/gio/gapplication.go:921 +0x1a fp=0xc0004acb10 sp=0xc0004acaf8 pc=0x63637a
runtime.call16(0xc000108d80, 0xc000425fd0, 0x0, 0x0, 0x0, 0x8, 0xc0004ad060)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:747 +0x43 fp=0xc0004acb30 sp=0xc0004acb10 pc=0x46b223
runtime.reflectcall(0xa41fc0?, 0x7ffcb9a27c10?, 0x1?, 0xb99d20?, 0x0?, 0x12?, 0xa41fc0?)
	<autogenerated>:1 +0x36 fp=0xc0004acb70 sp=0xc0004acb30 pc=0x46f616
reflect.Value.call({0xa43e40?, 0xc000425fd0?, 0x7d3acc133290?}, {0xb8b11c, 0x4}, {0xc000462e88, 0x1, 0xc0004ad1e8?})
	/opt/hostedtoolcache/go/1.21.8/x64/src/reflect/value.go:596 +0xce7 fp=0xc0004ad180 sp=0xc0004acb70 pc=0x4d89c7
reflect.Value.Call({0xa43e40?, 0xc000425fd0?, 0x37?}, {0xc000462e88?, 0x2?, 0x614ef0?})
	/opt/hostedtoolcache/go/1.21.8/x64/src/reflect/value.go:380 +0xb9 fp=0xc0004ad1f8 sp=0xc0004ad180 pc=0x4d7a99
github.com/jwijenbergh/purego.callbackWrap(0x7ffcb9a27b80)
	/home/runner/go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240126093400-70ff3a61df13/syscall_sysv.go:271 +0x3e8 fp=0xc0004ad2d8 sp=0xc0004ad1f8 pc=0x5ffe48
runtime.cgocallbackg1(0x5ffa60, 0xc0004ad498?, 0x0)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/cgocall.go:399 +0x2c2 fp=0xc0004ad3a8 sp=0xc0004ad2d8 pc=0x409a22
runtime.cgocallbackg(0x44513c?, 0xc0000061a0?, 0x300000002?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/cgocall.go:315 +0x125 fp=0xc0004ad438 sp=0xc0004ad3a8 pc=0x4096c5
runtime.cgocallbackg(0x5ffa60, 0x7ffcb9a27b80, 0x0)
	<autogenerated>:1 +0x29 fp=0xc0004ad460 sp=0xc0004ad438 pc=0x46f229
runtime.cgocallback(0xc0004ad4c0, 0x409315, 0x6002a0)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1035 +0xcc fp=0xc0004ad488 sp=0xc0004ad460 pc=0x46ca6c
runtime.systemstack_switch()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:474 +0x8 fp=0xc0004ad498 sp=0xc0004ad488 pc=0x46ace8
runtime.cgocall(0x6002a0, 0xc0004921c0)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/cgocall.go:175 +0x75 fp=0xc0004ad4d0 sp=0xc0004ad498 pc=0x409315
github.com/jwijenbergh/purego.RegisterFunc.func1({0xc00007e0a0?, 0x3?, 0x3?})
	/home/runner/go/pkg/mod/github.com/jwijenbergh/purego@v0.0.0-20240126093400-70ff3a61df13/func.go:253 +0xc65 fp=0xc0004ad8b8 sp=0xc0004ad4d0 pc=0x5fe1e5
reflect.callReflect(0xc00039a3f0, 0xc0004ade18, 0xc0004adcf0, 0xc0004adcf8)
	/opt/hostedtoolcache/go/1.21.8/x64/src/reflect/value.go:782 +0x54b fp=0xc0004adca0 sp=0xc0004ad8b8 pc=0x4d9f4b
reflect.callReflect(0xc00039a3f0, 0xc00014fe18, 0xc00014fcf0, 0xc00014fcf8)
	<autogenerated>:1 +0x45 fp=0xc0004adcd0 sp=0xc0004adca0 pc=0x4ea985
reflect.makeFuncStub()
	/opt/hostedtoolcache/go/1.21.8/x64/src/reflect/asm_amd64.s:47 +0x6e fp=0xc0004ade18 sp=0xc0004adcd0 pc=0x4e6d0e
github.com/jwijenbergh/puregotk/v4/gio.(*Application).Run(...)
	/home/runner/go/pkg/mod/github.com/jwijenbergh/puregotk@v0.0.0-20240305120901-acaa168affb9/v4/gio/gapplication.go:669
main.(*ui).Run(0xc000425f20, {0xc000425f60, 0x1, 0x1})
	/home/runner/work/linux-app/linux-app/cmd/geteduroam-gui/main.go:397 +0x13a fp=0xc0004ade80 sp=0xc0004ade18 pc=0x99645a
main.main()
	/home/runner/work/linux-app/linux-app/cmd/geteduroam-gui/main.go:465 +0x3d7 fp=0xc0004adf40 sp=0xc0004ade80 pc=0x996937
runtime.main()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:267 +0x2bb fp=0xc0004adfe0 sp=0xc0004adf40 pc=0x43d85b
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0004adfe8 sp=0xc0004adfe0 pc=0x46ccc1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005afa8 sp=0xc00005af88 pc=0x43dcae
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:404
runtime.forcegchelper()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:322 +0xb3 fp=0xc00005afe0 sp=0xc00005afa8 pc=0x43db33
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005afe8 sp=0xc00005afe0 pc=0x46ccc1
created by runtime.init.6 in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005b778 sp=0xc00005b758 pc=0x43dcae
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgcsweep.go:321 +0xdf fp=0xc00005b7c8 sp=0xc00005b778 pc=0x429c1f
runtime.gcenable.func1()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:200 +0x25 fp=0xc00005b7e0 sp=0xc00005b7c8 pc=0x41ed85
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005b7e8 sp=0xc00005b7e0 pc=0x46ccc1
created by runtime.gcenable in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000036070?, 0xcb0be8?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005bf70 sp=0xc00005bf50 pc=0x43dcae
runtime.goparkunlock(...)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1215080)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00005bfa0 sp=0xc00005bf70 pc=0x4274a9
runtime.bgscavenge(0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc00005bfc8 sp=0xc00005bfa0 pc=0x427a59
runtime.gcenable.func2()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:201 +0x25 fp=0xc00005bfe0 sp=0xc00005bfc8 pc=0x41ed25
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x46ccc1
created by runtime.gcenable in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x198?, 0xb68880?, 0x1?, 0xee?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005a620 sp=0xc00005a600 pc=0x43dcae
runtime.runfinq()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mfinal.go:193 +0x107 fp=0xc00005a7e0 sp=0xc00005a620 pc=0x41dda7
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0x46ccc1
created by runtime.createfing in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mfinal.go:163 +0x3d

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005c750 sp=0xc00005c730 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc00005c7e0 sp=0xc00005c750 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x1a73bbedbd4b8?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc000056750 sp=0xc000056730 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000567e0 sp=0xc000056750 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000567e8 sp=0xc0000567e0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x1a73bbedbd8b4?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc000056f50 sp=0xc000056f30 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc000056fe0 sp=0xc000056f50 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x1a73bbedc5a00?, 0x1?, 0xa6?, 0xa2?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005cf50 sp=0xc00005cf30 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc00005cfe0 sp=0xc00005cf50 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1a73bbedbd573?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc000508750 sp=0xc000508730 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc0005087e0 sp=0xc000508750 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0005087e8 sp=0xc0005087e0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x1a73bbedbd69f?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc000057750 sp=0xc000057730 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000577e0 sp=0xc000057750 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000577e8 sp=0xc0000577e0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1a73bbedbdcc3?, 0x1?, 0xb5?, 0x1f?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005d750 sp=0xc00005d730 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc00005d7e0 sp=0xc00005d750 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x1a73bbedbdfef?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/proc.go:398 +0xce fp=0xc00005df50 sp=0xc00005df30 pc=0x43dcae
runtime.gcBgMarkWorker()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1295 +0xe5 fp=0xc00005dfe0 sp=0xc00005df50 pc=0x420905
runtime.goexit()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x46ccc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/mgc.go:1219 +0x1c

rax    0x0
rbx    0x1
rcx    0x111
rdx    0x7d3b15e1ace0
rdi    0x1db2870
rsi    0x7d3b15e1ace0
rbp    0x7ffcb9a274a0
rsp    0x7ffcb9a27400
r8     0x1db2770
r9     0x7fffffff
r10    0x0
r11    0xb0f5cc0ce72684de
r12    0x6
r13    0x0
r14    0x7d3acc9fed08
r15    0x7d3acc9fed90
rip    0x7d3acc927167
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

**Comment by Txikivasco** [comment]
Geteduroam not connecting with Ubuntu 24.04

**Comment by jwijenbergh** [comment]
@martinpescador sorry for the late reply, I didn't see it. Can you test #54?

**Comment by martinpescador** [comment]
> @martinpescador sorry for the late reply, I didn't see it. Can you test #54?

Yes, possibly; though unsure what exactly it is that you want me to test?

**Comment by jwijenbergh** [comment]
Don't worry, I will release a new version soon

**Comment by jwijenbergh** [comment]
@martinpescador see https://github.com/geteduroam/linux-app/releases/tag/0.4
