### ISSUE TITLE
Getting "Authorization failed" with the rpm

### ISSUE THREAD

**Issue by VfBfoerst** [geteduroam/linux-app#55]
Hi :)  
I cannot configure eduroam with the packages installed with the rpm files, neither with the gui nor with the cli.  
I tried version 0.4 and 0.3. I am running Opensuse Tumbleweed.  I always get this error message when i try to authenticate:  
![image](https://github.com/user-attachments/assets/ab40450d-44e0-456e-8a0b-9721cbf6179d)
  
In debug mode, the cli produces the following error output:  
  
```bash
time=2024-11-14T19:10:35.629+01:00 level=ERROR msg="Could not obtain eap config with OAuth" error="failed to decode JSON: json: cannot unmarshal number 899.9999999 into Go struct field TokenResponse.expires_in of type int64"
``` 
Am I doing somethin wrong?

**Comment by jwijenbergh** [comment]
You're not doing something wrong. It seems that the server is returning some bogus data, or that my code has a bug somewhere :^). Investigating...

**Comment by jwijenbergh** [comment]
If you don't mind letting this be known publicly, which organization is this?

**Comment by VfBfoerst** [comment]
> If you don't mind letting this be known publicly, which organization is this?

```bash 
Found the following matches: 
[1] Universität Bamberg
```

**Comment by jwijenbergh** [comment]
Hi, sorry for the long wait. This seems to be an issue with the server from your institution. It would be best to contact them about this

**Comment by VfBfoerst** [comment]
okay, thank you anyway :)
